# Generated by Django 3.0.2 on 2020-02-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUTRReg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
