# Generated by Django 3.0.2 on 2020-02-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUTRReg', '0002_auto_20200201_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sca_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
