# Generated by Django 2.2.2 on 2019-07-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUTRReg', '0002_auto_20190714_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attended',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
