# Generated by Django 3.0.2 on 2020-02-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUTRReg', '0003_auto_20200201_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='loc_reqs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='pre_reqs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='student_reqs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalclass',
            name='loc_reqs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalclass',
            name='pre_reqs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalclass',
            name='student_reqs',
            field=models.TextField(null=True),
        ),
    ]
