# Generated by Django 3.0.2 on 2020-02-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUTRReg', '0004_auto_20200204_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalclass',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
