# Generated by Django 3.0.2 on 2020-02-05 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUTRReg', '0005_auto_20200204_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='apt_num',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='postal_cd',
            field=models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='You have entered an invalid Postal Code. Please enter a valid Canadian or US Postal Code', regex='^\\d{5}-\\d{4}|\\d{5}|[A-Z]\\d[A-Z] \\d[A-Z]\\d$')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='apt_num',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='location_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='postal_cd',
            field=models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='You have entered an invalid Postal Code. Please enter a valid Canadian or US Postal Code', regex='^\\d{5}-\\d{4}|\\d{5}|[A-Z]\\d[A-Z] \\d[A-Z]\\d$')]),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
