# Generated by Django 3.2.6 on 2021-08-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUTRReg', '0008_auto_20210529_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
