# Generated by Django 3.2.6 on 2021-09-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUTRReg', '0009_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TUTRReg.person'),
        ),
    ]
